name: Test and deploy

on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: Runs tests
    environment: CI
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.13
      - name: Install deps
        run: make install-requirements
      - name: Runs test
        run: make test
        env:
          API_HOST: ${{ vars.API_HOST }}
          API_PORT: ${{ vars.API_PORT}}
          TEST_API_PORT: ${{ vars.TEST_API_PORT }}
          TEST_API_HOST: ${{ vars.TEST_API_HOST }}
          MAKE_IMAGE_NAME: ${{ vars.MAKE_IMAGE_NAME}}
          MAKE_CONTAINER_NAME: ${{ vars.MAKE_CONTAINER_NAME}}
          MAKE_HOST_PORT: ${{ vars.MAKE_HOST_PORT}}
