name: Test and deploy

on: [push, workflow_dispatch]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    environment: CI
    env:
      API_HOST: ${{ vars.API_HOST }}
      API_PORT: ${{ vars.API_PORT}}
      TEST_API_PORT: ${{ vars.TEST_API_PORT }}
      TEST_API_HOST: ${{ vars.TEST_API_HOST }}
      MAKE_IMAGE_NAME: ${{ vars.MAKE_IMAGE_NAME}}
      MAKE_CONTAINER_NAME: ${{ vars.MAKE_CONTAINER_NAME}}
      MAKE_HOST_PORT: ${{ vars.MAKE_HOST_PORT}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.13
      - name: Create a fake .env
        run: touch .env
      - name: Install requirement
        run: make install-requirements
      # If there is no .env the make command won't work
      # Injecting directly the variables in the makefile would be a big security risk by forcing us to commit the env vars
      - name: Run the api
        run: make run
      - name: Run the tests
        run: make test-api
